#!/bin/sh

start()
{
	printf 'Starting network: '
	mkdir -p /run/network
	if ip link set dev lo up; then
		echo "OK"
	else
		echo "FAIL"
		return 1
	fi
}

stop()
{
	printf 'Stopping network: '
	if ip link set dev lo down; then
		echo "OK"
	else
		echo "FAIL"
		return 1
	fi
}

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
restart|reload)
	stop
	start
	;;
*)
	echo "Usage: $0 {start|stop|restart|reload}" >&2
	exit 1
	;;
esac
