# uMTP-Responder configuration for the ePass USB gadget.

loop_on_disconnect 1

storage "/media" "media" "rw"

manufacturer "Rhodes Island"
product "Electric Pass"
serial "ePass001"
firmware_version "Rev A"
mtp_extensions "microsoft.com: 1.0; android.com: 1.0;"
interface "MTP"

usb_vendor_id 0x1d6b
usb_product_id 0x0200
usb_class 0x6
usb_subclass 0x1
usb_protocol 0x1
usb_dev_version 0x0101

usb_functionfs_mode 0x1
usb_dev_path "/dev/ffs-mtp/ep0"
usb_epin_path "/dev/ffs-mtp/ep1"
usb_epout_path "/dev/ffs-mtp/ep2"
usb_epint_path "/dev/ffs-mtp/ep3"
usb_max_rd_buffer_size 0x200
usb_max_wr_buffer_size 0x200
read_buffer_cache_size 0x4000
usb_max_packet_size 0x200
